# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.0"
manifest_format = "2.0"
project_hash = "14e4a45c8da871af702dba1cd429c84c71914f70"

[[deps.LineWorlds]]
path = "../../LineWorlds"
uuid = "378ae85f-3ccf-4c92-8c74-de8c49c343b8"
version = "0.1.0"
